### ISSUE TITLE
Export to image and PDF not working in example

### ISSUE THREAD

**Issue by sabski** [flexmonster/pivot-requirejs#1]
I was playing around with example and the export for image and pdf are not working.

![image](https://user-images.githubusercontent.com/3330454/172362990-aa91804b-1887-47da-b36f-a98363091f66.png)

**Comment by solja484** [comment]
Thank you for reporting this issue.

We have researched it and figured out that such behavior appeared after the 2.9.10 version of Flexmonster when the mentioned libraries were updated.

We will fix this inconsistency till the next minor release on ETA June 27.

Feel free to contact us in case of any other questions.

**Comment by solja484** [comment]
We are glad to inform you that the issue with exporting to PDF and image using RequireJS was fixed.

This fix is provided in the 2.9.28 version of Flexmonster: [https://www.flexmonster.com/release-notes/version-2-9-28/](https://www.flexmonster.com/release-notes/version-2-9-28/).

You are welcome to update the component. Here is our upgrading guide: [https://www.flexmonster.com/doc/updating-to-the-latest-version/](https://www.flexmonster.com/doc/updating-to-the-latest-version/).

Please let us know if the fix works fine for you.

**Comment by sabski** [comment]
Yes, this fix works thank you.

**Comment by solja484** [comment]
Thank you for the feedback. 
We are glad to hear the fix works well.

Feel free to contact us if any other questions arise.
